services:
  db:
    image: postgres
    shm_size: 128mb
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=metastore_db"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

  # make sure that you specify correct volume to be mounted
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_PROMETHEUS_URL=http://prometheus:9090
      - MINIO_PROMETHEUS_JOB_ID=minio-job
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9090:9090
    command: server /data --console-address ":9090"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add local http://minio:9000 or minioadmin minioadmin;
      /usr/bin/mc rm -r --force local/mydata-tap-dev-s3-etl;
      /usr/bin/mc mb local/mydata-tap-dev-s3-etl;
      /usr/bin/mc policy download local/mydata-tap-dev-s3-etl;
      /usr/bin/mc rm -r --force local/mydata-tap-dev-s3-datalake;
      /usr/bin/mc mb local/mydata-tap-dev-s3-datalake;
      /usr/bin/mc policy download local/mydata-tap-dev-s3-datalake;
      exit 0;
      "

  prometheus:
    image: prom/prometheus
#    ports:
#      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus

  metastore:
    build: ./metastore/
    image: tap/metastore:3.0.0
    ports:
      - 9083:9083
    volumes:
      - type: bind
        source: metastore/conf/metastore-site.xml
        target: /opt/hive-metastore/conf/metastore-site.xml
    depends_on:
      - db
      - minio
      - createbuckets

  hiveserver:
    build: ./hiveserver/
    image: tap/hiveserver:3.1.3
    ports:
      - "10000:10000"
      - "10002:10002"
    environment:
      HIVE_SERVER2_THRIFT_PORT: 10000
      HIVE_SERVER2_THRIFT_BIND_HOST: 0.0.0.0
      SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083'
      IS_RESUME: 'true'
      SERVICE_NAME: 'hiveserver2'
    depends_on:
      - metastore
volumes:
  postgresql:
    external: true