version: "2"

services:
  mariadb:
    image: mariadb:latest
#    ports:
#      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  # make sure that you specify correct volume to be mounted
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_PROMETHEUS_URL=http://prometheus:9090
      - MINIO_PROMETHEUS_JOB_ID=minio-job
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9090:9090
    command: server /data --console-address ":9090"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add local http://minio:9000 or minioadmin minioadmin;
      /usr/bin/mc rm -r --force local/mydata-tap-dev-s3-etl;
      /usr/bin/mc mb local/mydata-tap-dev-s3-etl;
      /usr/bin/mc policy download local/mydata-tap-dev-s3-etl;
      /usr/bin/mc rm -r --force local/mydata-tap-dev-s3-datalake;
      /usr/bin/mc mb local/mydata-tap-dev-s3-datalake;
      /usr/bin/mc policy download local/mydata-tap-dev-s3-datalake;
      exit 0;
      "

  prometheus:
    image: prom/prometheus
#    ports:
#      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus

  hive-metastore:
    build: .
    image: hive-metastore:latest
    ports:
    - 9083:9083
    depends_on:
      - mariadb
      - minio
      - createbuckets
